name: glibc
# This workflow tests examples from the examples directory of this repo.

on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      version:
        default: import/2.39-7

jobs:
  do-test:
    strategy:
      fail-fast: false
      matrix:
        version: [  eb4181e9f4a512de37dad4ba623c921671584dea, 09c6c6073c925235b385af1d8edf6bc853eeaf60, dd31f42e39206bc69f4a60e47ee117f6c968138c, e6f3fe362f1aab78b1448d69ecdbd9e3872636d3, a8e72913fea0c6e2832c50523c60907ffa3b753b]
        testNum: [1,2,3] #[1,2,3,4,5,6,7,8,9,10]
        os: [ ubuntu-22.04-arm ]
    runs-on: ${{ matrix.os }}
    
    timeout-minutes: 25
    steps:
      - name: vm info
        run: |
          curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq      
          echo '::warning:: ' $(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq | grep "vmSize")
          sudo sysctl -w kernel.print-fatal-signals=1

      # git clone https://git.launchpad.net/~ubuntu-core-dev/ubuntu/+source/glibc glibc
      - name: clone glibc
        run: |
          mkdir $HOME/src
          cd $HOME/src
          git clone https://github.com/mitesch/glibc-mirror glibc
          cd glibc
          git checkout ${{ matrix.version }}
          mkdir -p $HOME/build/glibc
        
      - name: build glibc
        run: |
          cd $HOME/build/glibc
          sed -i 's/^# PARALLELMFLAGS/PARALLELMFLAGS/' $HOME/src/glibc/Makefile.in
          $HOME/src/glibc/configure --prefix=/usr
          make

      - uses: actions/checkout@v4
      - name: test rustc
        run: |
          pwd
          cd $GITHUB_WORKSPACE
          pwd
          pip install pyyaml
          chmod +x runtasks.py
          ./runtasks.py tasks-ubuntuglibc-239.yml 


