name: glibc
# This workflow tests examples from the examples directory of this repo.

on:
  workflow_dispatch:

jobs:
  example:
    strategy:
      fail-fast: false
      matrix:
        version: [glibc-2.35, glibc-2.36, glibc-2.37, glibc-2.38, glibc-2.39, c804cd1c00adde061ca51711f63068c103e94eef]
        os: [ ubuntu-22.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: vm info
        run: |
          curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq      
          echo '::warning:: ' $(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq | grep "vmSize")
          sudo sysctl -w kernel.print-fatal-signals=1

      - name: clone glibc
        run: |
          mkdir $HOME/src
          cd $HOME/src
          git clone https://github.com/mitesch/glibc-mirror glibc
          cd glibc
          git checkout ${{ matrix.version }}
          mkdir -p $HOME/build/glibc
        
      - name: build glibc
        run: |
          cd $HOME/build/glibc
          sed -i 's/^# PARALLELMFLAGS/PARALLELMFLAGS/' $HOME/src/glibc/Makefile.in
          $HOME/src/glibc/configure --prefix=/usr
          make
          make install
          
      - uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: glibc-${{ matrix.version }}
          path: |
            /home/runner/build

      - name: test rustc
        run: |
          cd $HOME/build/glibc
          sudo ldconfig /home/runner/build/glibc
          ./testrun.sh rustc --version


