name: glibc
# This workflow tests examples from the examples directory of this repo.

on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      version:
        default: import/2.39-7

jobs:
  do-test:
    strategy:
      fail-fast: false
      matrix:
        version: [  glibc-2.35, glibc-2.35.9000, glibc-2.36, glibc-2.36.9000, glibc-2.37, glibc-2.37.9000, glibc-2.38, glibc-2.38.9000, glibc-2.39, glibc-2.39.9000]
        testNum: [1,2,3] #[1,2,3,4,5,6,7,8,9,10]
        os: [ ubuntu-22.04-arm ]
    runs-on: ${{ matrix.os }}
    
    timeout-minutes: 25
    steps:
      - name: vm info
        run: |
          curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq      
          echo '::warning:: ' $(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq | grep "vmSize")
          sudo sysctl -w kernel.print-fatal-signals=1

      # git clone https://git.launchpad.net/~ubuntu-core-dev/ubuntu/+source/glibc glibc
      - name: clone glibc
        run: |
          mkdir $HOME/src
          cd $HOME/src
          git clone https://github.com/mitesch/glibc-mirror glibc
          cd glibc
          git checkout ${{ matrix.version }}
          mkdir -p $HOME/build/glibc
        
      - name: build glibc
        run: |
          cd $HOME/build/glibc
          sed -i 's/^# PARALLELMFLAGS/PARALLELMFLAGS/' $HOME/src/glibc/Makefile.in
          $HOME/src/glibc/configure --prefix=/usr
          make

      - uses: actions/checkout@v4
      - name: test rustc
        run: |
          pwd
          cd $GITHUB_WORKSPACE
          pwd
          pip install pyyaml
          chmod +x runtasks.py
          ./runtasks.py -q  tasks-ubuntuglibc-239.yml 


